#!/bin/sh

sudo apt-get install build-essential libfltk1.3-dev libboost-all-dev libopencv-dev portaudio19-dev cmake

BRANCH=master
if [ $# -gt 0 ]; then
	BRANCH=$1
fi

rm -rf sk-$BRANCH

wget -O sk-$BRANCH.zip https://github.com/cpaproth/sk/archive/$BRANCH.zip || return
unzip sk-$BRANCH.zip
mkdir sk-$BRANCH/build || return
cd sk-$BRANCH/build
cmake -D CMAKE_BUILD_TYPE=Release ../src/
make
cd ../..
cp sk-$BRANCH/build/sk sk

rm sk-$BRANCH.zip
rm -rf sk-$BRANCH

./sk
