// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef ui_h
#define ui_h
#include <fltk/Window.h>
#include <map>
#include <string>
#include <boost/function/function0.hpp>
#include <fltk/run.h>
#include <fltk/Preferences.h>
#include <fltk/xpmImage.h>
#include "GlImage.h"
#include "GlTable.h"
#include <fltk/TabGroup.h>
#include <fltk/Group.h>
#include <fltk/RadioButton.h>
#include <fltk/Button.h>
#include <fltk/CheckButton.h>
#include <fltk/Input.h>
#include <fltk/ValueInput.h>
#include <fltk/TextDisplay.h>

namespace SK  {

namespace images  {
}

class UILock  {
public:
  UILock();
  ~UILock();
};

class UIUnlock  {
public:
  UIUnlock();
  ~UIUnlock();
};

class UserInterface  {
  fltk::Preferences prefs;
public:
  std::map<std::string, boost::function<void(void)> > f;
  UserInterface(void);
private:
  fltk::Window *mainwnd;
  inline void cb_mainwnd_i(fltk::Window*, void*);
  static void cb_mainwnd(fltk::Window*, void*);
public:
        GlTable *table;
        GlImage *leftimage;
        GlImage *rightimage;
        GlImage *midimage;
          fltk::Group *trump;
private:
          inline void cb_trump_i(fltk::Group*, void*);
          static void cb_trump(fltk::Group*, void*);
public:
            fltk::RadioButton *diamonds;
private:
            inline void cb_diamonds_i(fltk::RadioButton*, void*);
            static void cb_diamonds(fltk::RadioButton*, void*);
public:
            fltk::RadioButton *hearts;
private:
            inline void cb_hearts_i(fltk::RadioButton*, void*);
            static void cb_hearts(fltk::RadioButton*, void*);
public:
            fltk::RadioButton *spades;
private:
            inline void cb_spades_i(fltk::RadioButton*, void*);
            static void cb_spades(fltk::RadioButton*, void*);
public:
            fltk::RadioButton *clubs;
private:
            inline void cb_clubs_i(fltk::RadioButton*, void*);
            static void cb_clubs(fltk::RadioButton*, void*);
public:
            fltk::RadioButton *grand;
private:
            inline void cb_grand_i(fltk::RadioButton*, void*);
            static void cb_grand(fltk::RadioButton*, void*);
public:
            fltk::RadioButton *null;
private:
            inline void cb_null_i(fltk::RadioButton*, void*);
            static void cb_null(fltk::RadioButton*, void*);
public:
            fltk::RadioButton *nullouvert;
private:
            inline void cb_nullouvert_i(fltk::RadioButton*, void*);
            static void cb_nullouvert(fltk::RadioButton*, void*);
public:
          fltk::Button *hand;
private:
          inline void cb_hand_i(fltk::Button*, void*);
          static void cb_hand(fltk::Button*, void*);
public:
          fltk::Group *extra;
private:
          inline void cb_extra_i(fltk::Group*, void*);
          static void cb_extra(fltk::Group*, void*);
public:
            fltk::CheckButton *schneider;
private:
            inline void cb_schneider_i(fltk::CheckButton*, void*);
            static void cb_schneider(fltk::CheckButton*, void*);
public:
            fltk::CheckButton *schwarz;
private:
            inline void cb_schwarz_i(fltk::CheckButton*, void*);
            static void cb_schwarz(fltk::CheckButton*, void*);
public:
            fltk::CheckButton *ouvert;
private:
            inline void cb_ouvert_i(fltk::CheckButton*, void*);
            static void cb_ouvert(fltk::CheckButton*, void*);
public:
          fltk::Button *play;
private:
          inline void cb_play_i(fltk::Button*, void*);
          static void cb_play(fltk::Button*, void*);
          inline void cb_Neustart_i(fltk::Button*, void*);
          static void cb_Neustart(fltk::Button*, void*);
          inline void cb_Mikrofon_i(fltk::CheckButton*, void*);
          static void cb_Mikrofon(fltk::CheckButton*, void*);
public:
          fltk::Input *address;
private:
          inline void cb_address_i(fltk::Input*, void*);
          static void cb_address(fltk::Input*, void*);
public:
          fltk::ValueInput *port;
private:
          inline void cb_port_i(fltk::ValueInput*, void*);
          static void cb_port(fltk::ValueInput*, void*);
public:
          fltk::ValueInput *bandwidth;
private:
          inline void cb_bandwidth_i(fltk::ValueInput*, void*);
          static void cb_bandwidth(fltk::ValueInput*, void*);
          inline void cb_Start_i(fltk::Button*, void*);
          static void cb_Start(fltk::Button*, void*);
          inline void cb_Stats_i(fltk::Button*, void*);
          static void cb_Stats(fltk::Button*, void*);
public:
          fltk::CheckButton *autostart;
private:
          inline void cb_autostart_i(fltk::CheckButton*, void*);
          static void cb_autostart(fltk::CheckButton*, void*);
public:
          fltk::Input *name;
private:
          inline void cb_name_i(fltk::Input*, void*);
          static void cb_name(fltk::Input*, void*);
public:
        fltk::TextDisplay *log;
  ~UserInterface(void);
private:
  UserInterface(const UserInterface&);
  void operator=(const UserInterface&);
};
}
#endif
